[package]
name = "migration"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm-migration = { version = "=2.0.0-rc.32", features = [
    "runtime-tokio-native-tls",
    "sqlx-postgres",
] }
tokio = { version = "=1.49.0", features = ["macros", "rt-multi-thread"] }
