apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: t-rader
type: Opaque
stringData:
  # デプロイ先の環境に合わせて書き換えること
  DATABASE_URL: 'postgres://t_rader:t_rader@timescaledb.t-rader.svc.cluster.local:5432/t_rader'
